game_info = {
    'Budget': 0,
    'Cash': 3000000000,
    'Num Personnel': 250,
    'Staff Assignments': {
        'Intel': 80,
        'Acquisitions': 100,
        'Cyber': 20,
        'Ops': 20,
        'Unassigned': 30
    },
    'Reputation': 0,
    'Game Score': 0,
    'Num Sats': 0,
    'Sats Owned': [],
    'Max Budget': 0,
    'Max Personnel': 0,
    'Total Cash': 0,
    'Date Started': "",
    'Cyber Def Level': 0,
    'Cyber Off Level': 0,
    'Acq GPS Level': 0,
    'Acq ABD Level': 0,
    'Acq SPI Level': 0,
    'Acq MDef Level': 0,
    'Acq ABCDE Level': 0,
    'Acq IROOI Level': 0,
    'Acq ICBM Level': 0,
    'Acq B.O.L.L.S. Level': 0,
    'Acq Nukes Level': 0,
    'Reels Seen': [],
    'Ground Killed': 0,
    'Air Killed': 0,
    'Ground KIA': 0,
    'Air KIA': 0
}
