game_info = {'budget': 0,
             'cash': 1000,
             'num_personnel': 230,
             'Staff Assignments': {'Intel': 80,
                                   'Acquisitions': 100,
                                   'Cyber': 20,
                                   'Ops': 20,
                                   'Unassigned': 30},
             'reputation': 0,
             'num_sats': 0,
             'sats_owned': [],
             'max_budget': 0,
             'max_personnel': 0,
             'total_cash': 0,
             'date_started': "",
             'Cyber Def Level': 0,
             'Cyber Off Level': 0,
             'Acq GPS Level': 0,
             'Acq ABD Level': 0,
             'Acq SPI Level': 0,
             'Acq MDef Level': 0,
             'Acq ABCDE Level': 0,
             'Acq IROOI Level': 0,
             'Acq ICBM Level': 0,
             'Acq B.O.L.L.S. Level': 0,
             'Acq Nukes Level': 0,
             'Reels Seen': []}
