"""
The data for every node. The format is as follows:

'name' -> The name of the node. This will be shown on the node itself
'desc'-> The description of the node. This will be shown in the node's tooltip
'color' -> The color of the node's body.
'cost' -> The monetary cost to purchase the node.
'parent' -> The name of the parent of this node. *name, not a reference to
'children' -> The names of the children of this node. *names, not references to
'generation' -> The generation of this node.
'index' -> A number that helps with the spacing of the nodes
'dist' -> The distance between this node and it's parent
"""


main_data = [{'name': 'EARTH',
            'desc': 'Home sweet home',
            'color': 'white',
            'cost': 0,
            'is_zoomable': True,
            'parent': None,
            'children': ['ACQUISITIONS', 'OPS', 'PERSONNEL', 'INTEL', 'CYBER',
                         'GSSAP', 'ISS', 'MILSTAR', 'SBIRS', 'AEHF', 'GPS'],
            'generation': 0,
            'index': 0,
            'dist': 0},

            {'name': 'ACQUISITIONS',
            'desc': 'Acquire cool shit',
            'color': 'orange',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 1,
            'index': 1,
            'dist': 120},
            {'name': 'OPS',
            'desc': 'Go on space adventures',
            'color': 'orange',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 1,
            'index': 2,
            'dist': 120},
            {'name': 'PERSONNEL',
            'desc': 'Buy people. Not like that though',
            'color': 'orange',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 1,
            'index': 3,
            'dist': 120},
            {'name': 'INTEL',
            'desc': 'Knowledge',
            'color': 'orange',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 1,
            'index': 4,
            'dist': 120},
            {'name': 'CYBER',
            'desc': 'Fancy techy things',
            'color': 'orange',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 1,
            'index': 5,
            'dist': 120},

            {'name': 'GSSAP',
            'desc': 'A satellite',
            'color': 'red',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 5,
            'index': 1,
            'dist': 400},
            {'name': 'ISS',
            'desc': 'A space station',
            'color': 'red',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 5,
            'index': 2,
            'dist': 300},
            {'name': 'MILSTAR',
            'desc': 'A satellite',
            'color': 'red',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 5,
            'index': 3,
            'dist': 400},
            {'name': 'GPS',
            'desc': 'A satellite',
            'color': 'red',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 5,
            'index': 4,
            'dist': 400},
            {'name': 'AEHF',
            'desc': 'A satellite',
            'color': 'red',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 5,
            'index': 5,
            'dist': 400},
            {'name': 'SBIRS',
            'desc': 'A satellite',
            'color': 'red',
            'cost': 10,
            'is_zoomable': True,
            'parent': 'EARTH',
            'children': [],
            'generation': 5,
            'index': 6,
            'dist': 450}]

gssap_data = [{'name': 'GSSAP',
                'desc': 'A satellite used for observation and spy things',
                'color': 'red',
                'cost': 0,
                'is_zoomable': False,
                'parent': None,
                'children': ['PRICE-', 'BETTER ELECTRONICS', 'BETTER MATERIALS'],
                'generation': 0,
                'index': 0,
                'dist': 0},

                {'name': 'BETTER ELECTRONICS',
                'desc': 'General improvements to the onboard electronics',
                'color': 'orange',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'GSSAP',
                'children': ['ACCURACY+', 'AI ENHANCED TRACKING'],
                'generation': 1,
                'index': 1,
                'dist': 200},

                {'name': 'BETTER MATERIALS',
                'desc': 'Everything gets better',
                'color': 'orange',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'GSSAP',
                'children': ['SPEED', 'RESILIENCY'],
                'generation': 1,
                'index': 2,
                'dist': 140},

                {'name': 'PRICE-',
                'desc': 'Make each satellite a little cheaper',
                'color': 'orange',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'GSSAP',
                'children': ['PRICE--'],
                'generation': 1,
                'index': 3,
                'dist': 150},
                {'name': 'PRICE--',
                'desc': 'Only a few million dollars now',
                'color': 'mint',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'PRICE-',
                'children': ['PRICE---'],
                'generation': 2,
                'index': 1,
                'dist': 110},
                {'name': 'PRICE---',
                'desc': "Average school teacher salary",
                'color': 'skyblue',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'PRICE--',
                'children': [],
                'generation': 3,
                'index': 1,
                'dist': 110},

                {'name': 'SPEED',
                'desc': 'Faster movement means more sneaking around',
                'color': 'mint',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'BETTER MATERIALS',
                'children': ['SPEEEED'],
                'generation': 2,
                'index': 1,
                'dist': 110},
                {'name': 'SPEEEED',
                'desc': 'WEEEEEEEEEEEEEEE!!!!!',
                'color': 'skyblue',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'SPEED',
                'children': [],
                'generation': 3,
                'index': 1,
                'dist': 110},
                {'name': 'RESILIENCY',
                'desc': 'Basically HP',
                'color': 'mint',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'BETTER MATERIALS',
                'children': [],
                'generation': 2,
                'index': 2,
                'dist': 110},

                {'name': 'AI ENHANCED TRACKING',
                'desc': 'Adds an AI system (Buzz) to aid in tracking',
                'color': 'mint',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'BETTER ELECTRONICS',
                'children': [],
                'generation': 2,
                'index': 2,
                'dist': 120},

                {'name': 'ACCURACY+',
                'desc': 'You can now distingush between a tank and a smart car',
                'color': 'mint',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'BETTER ELECTRONICS',
                'children': ['ACCURACY++'],
                'generation': 2,
                'index': 1,
                'dist': 140},
                {'name': 'ACCURACY++',
                'desc': 'You can watch a mosquito fly around NYC with ease',
                'color': 'skyblue',
                'cost': 10,
                'is_zoomable': False,
                'parent': 'ACCURACY+',
                'children': [],
                'generation': 3,
                'index': 1,
                'dist': 110}]

iss_data = [{'name': 'ISS',
            'desc': 'The OG international space station',
            'color': 'red',
            'cost': 0,
            'is_zoomable': False,
            'parent': None,
            'children': ['MORE LIVING SPACES', 'BETTER FOOD'],
            'generation': 0,
            'index': 0,
            'dist': 0},

            {'name': 'MORE LIVING SPACES',
            'desc': 'If more people can live here, more can get done',
            'color': 'orange',
            'cost': 10,
            'is_zoomable': False,
            'parent': 'ISS',
            'children': [],
            'generation': 1,
            'index': 1,
            'dist': 160},

            {'name': 'BETTER FOOD',
            'desc': 'Better food = more happiness',
            'color': 'orange',
            'cost': 10,
            'is_zoomable': False,
            'parent': 'ISS',
            'children': [],
            'generation': 1,
            'index': 2,
            'dist': 140}]

milstar_data = [{'name': 'MILSTAR',
                'desc': 'MILSTAR',
                'color': 'red',
                'cost': 0,
                'is_zoomable': False,
                'parent': None,
                'children': [],
                'generation': 0,
                'index': 0,
                'dist': 0}]

aehf_data = [{'name': 'AEHF',
                'desc': 'AEHF',
                'color': 'red',
                'cost': 0,
                'is_zoomable': False,
                'parent': None,
                'children': [],
                'generation': 0,
                'index': 0,
                'dist': 0}]

sbirs_data = [{'name': 'SBIRS',
                'desc': 'SBIRS',
                'color': 'red',
                'cost': 0,
                'is_zoomable': False,
                'parent': None,
                'children': [],
                'generation': 0,
                'index': 0,
                'dist': 0}]

gps_data = [{'name': 'GPS',
                'desc': 'GPS',
                'color': 'red',
                'cost': 0,
                'is_zoomable': False,
                'parent': None,
                'children': [],
                'generation': 0,
                'index': 0,
                'dist': 0}]
