node_data = [{'name': 'CENTER',
            'desc': 'center',
            'color': 'white',
            'cost': 0,
            'parent': None,
            'children': ['UP1', 'UP2', 'UP3'],
            'generation': 0},

            {'name': 'UP1',
            'desc': 'this is an upgrade',
            'color': 'orange',
            'cost': 10,
            'parent': 'CENTER',
            'children': ['UP11'],
            'generation': 1},
            {'name': 'UP2',
            'desc': 'this is an upgrade',
            'color': 'orange',
            'cost': 10,
            'parent': 'CENTER',
            'children': ['UP21', 'UP22', 'UP23'],
            'generation': 1},
            {'name': 'UP3',
            'desc': 'this is an upgrade',
            'color': 'orange',
            'cost': 10,
            'parent': 'CENTER',
            'children': [],
            'generation': 1},

            {'name': 'UP11',
            'desc': 'this is an upgrade',
            'color': 'mint',
            'cost': 10,
            'parent': 'UP1',
            'children': [],
            'generation': 2},
            {'name': 'UP21',
            'desc': 'this is an upgrade',
            'color': 'mint',
            'cost': 10,
            'parent': 'UP2',
            'children': [],
            'generation': 2},
            {'name': 'UP22',
            'desc': 'this is an upgrade',
            'color': 'mint',
            'cost': 10,
            'parent': 'UP2',
            'children': ['UP221', 'UP222'],
            'generation': 2},
            {'name': 'UP23',
            'desc': 'this is an upgrade',
            'color': 'mint',
            'cost': 10,
            'parent': 'UP2',
            'children': ['UP231', 'UP232', 'UP233'],
            'generation': 2},

            {'name': 'UP221',
            'desc': 'this is an upgrade',
            'color': 'skyblue',
            'cost': 10,
            'parent': 'UP22',
            'children': [],
            'generation': 3},
            {'name': 'UP222',
            'desc': 'this is an upgrade',
            'color': 'skyblue',
            'cost': 10,
            'parent': 'UP22',
            'children': [],
            'generation': 3},
            {'name': 'UP231',
            'desc': 'this is an upgrade',
            'color': 'skyblue',
            'cost': 10,
            'parent': 'UP23',
            'children': [],
            'generation': 3},
            {'name': 'UP232',
            'desc': 'this is an upgrade',
            'color': 'skyblue',
            'cost': 10,
            'parent': 'UP23',
            'children': [],
            'generation': 3},
            {'name': 'UP233',
            'desc': 'this is an upgrade',
            'color': 'skyblue',
            'cost': 10,
            'parent': 'UP23',
            'children': [],
            'generation': 3}]
