node_data = [{'name': 'CENTER',
            'desc': 'center',
            'color': 'white',
            'cost': 0,
            'parent': None,
            'children': ['UP1', 'UP2']},
            {'name': 'UP1',
            'desc': 'this is an upgrade',
            'color': 'red',
            'cost': 10,
            'parent': 'CENTER',
            'children': ['UP11']},
            {'name': 'UP11',
            'desc': 'this is an upgrade',
            'color': 'purple',
            'cost': 10,
            'parent': 'UP1',
            'children': []},
            {'name': 'UP2',
            'desc': 'this is an upgrade',
            'color': 'red',
            'cost': 10,
            'parent': 'CENTER',
            'children': ['UP21', 'UP22']},
            {'name': 'UP21',
            'desc': 'this is an upgrade',
            'color': 'purple',
            'cost': 10,
            'parent': 'UP2',
            'children': []},
            {'name': 'UP22',
            'desc': 'this is an upgrade',
            'color': 'purple',
            'cost': 10,
            'parent': 'UP2',
            'children': ['UP221']},
            {'name': 'UP221',
            'desc': 'this is an upgrade',
            'color': 'green',
            'cost': 10,
            'parent': 'UP22',
            'children': []}]
